blogs/urls.py
from django.urls import path
from . import views


app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),  # http://127.0.0.1:8000/へのアクセスに対してviews.indexメソッドを呼ぶ
    path('detail/<int:blog_id>/', views.detail, name='detail'),  # blog_idはviews.pyにも渡される
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),  # http://127.0.0.1:8000/にアクセスされた時は、blogs.urlsファイルを参照するよう設定
]

blogs/models.py
from django.db import models

# Create your models here.
# Pythonコードでデータベースの構造を記述し、簡単に操作できるようにmodelsを設定
class Blog(models.Model):
    title = models.CharField(blank=False, null=False, max_length=150)
    text = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        """オブジェクトを扱う上で使用するフィールドを指定
            ブログオブジェクトの一覧ページ（http://127.0.0.1:8000/admin/blogs/blog/）にいくと、それぞれのブログのタイトルが表示される
        """

blogs/views.py
from django.shortcuts import render
from .models import Blog

# Create your views here.
def index(request):
    blogs = Blog.objects.order_by('-created_datetime')  # クエリセットの取得
    return render(request, 'blogs/index.html', {'blogs': blogs})


def detail(request, blog_id):  # blogs/urls.pyに指定したblog_idを受け取る
    blog = Blog.objects.get(id=blog_id)
    return render(request, 'blogs/detail.html', {'blog': blog})

blogs/templates/blogs/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BlogApp</title>
</head>
<body>
    <h1 style="text-align: center;">{{ blog.title }}</h1>
    <div style="width: 70%; margin: 0px auto">
        <div>
            <div style="margin: 60px 20px;">
                {{ blog.text }}
            </div>
            <div style="text-align: center; margin-top: 50px">
                <a href="{% url 'blogs:index' %}">Goto TopPage</a>
            </div>
        </div>
    </div>
</body>
</html>

blogs/templates/blogs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1 style="text-align: center;">BlogSite</h1>
    <div style="width: 70%; margin: 0px auto;">
        <hr />
        {% for blog in blogs %}
        <div>
            <h3>{{ blog.title }}</h3>
            <!--truncatechars(テンプレートタグフィルター)を用いて100文字だけ表示するよう設定-->
            <div>{{ blog.text | truncatechars:100 }}</div>
            <div style="text-align: right">
                <!--このリンクがblogsアプリケーション内のurls.pyで「detail」と名前をつけたURLにリンクするよう設定-->
                <a href="{% url 'blogs:detail' blog_id=blog.id %}">記事を読む</a>
            </div>
        </div>
        <hr />
        {% endfor %}
    </div>
</body>
</html>